Improved vim servername guess, cleaned up a bit

diff --git a/coordinatex b/coordinatex
--- a/coordinatex
+++ b/coordinatex
@@ -222,9 +222,18 @@ if [ -z $OKAYEDITOR ]; then
 	exit 1
 fi
 if  [ -z "$VIMSERVER" ] && [ "$EDITOR" = "vim" ]; then
-	echo "ERROR: When using vim, must provide a vimserver name."
-	echo "See vim's \":help clientserver\""
-	exit 1
+	if [ $(vim --serverlist | wc -l) -eq 1 ]; then
+		VIMSERVER=$(vim --serverlist)
+		echo "WARNING: No vim server specified, guessing: $VIMSERVER"
+	elif [ $(for SERVER in $(vim --serverlist); do vim --servername "$SERVER" --remote-expr "bufname('.')" ; done | grep "[.]tex$" | wc -l) -eq 1 ]; then
+		VIMSERVER=$(for SERVER in $(vim --serverlist); do vim --servername "$SERVER" --remote-expr "bufname('.')"; echo $SERVER; done | awk 'NEXT{print$0}/[.]tex$/{NEXT=1}')
+		echo "WARNING: No vim server specified, guessing: $VIMSERVER"
+	else
+		echo "ERROR: When using vim, must provide a vimserver name."
+		echo "Could got guess the vim servername, aborting."
+		echo "See vim's \":help clientserver\""
+		exit 1
+	fi
 fi
 
 #  Check for READER
@@ -374,39 +383,3 @@ SEARCHPID=$!
 echo "Press ENTER to quit"
 read DUMMYVAR
 quit
-
-
-
-#export COORDCOMPILEPID="-1"
-#export COORDSEARCHPID="-1"
-#
-#echo "done."
-#
-## don't want ctrl-c to quit without cleaning up
-#trap coordquit INT
-#
-#echo -n "Starting automatic compilation loop... "
-#coordcompile.sh "test.tex" "$EDITOR2"&
-#COORDCOMPILEPID=$!
-#if ps $COORDCOMPILEPID >/dev/null; then
-#	echo "PID=$COORDCOMPILEPID"
-#else
-#	echo "Couldn't start compilation loop, aborting."
-#	exit
-#fi
-#
-#echo -n "Starting editor-viewer-sync loop... "
-#coordsearch.sh "test.tex" "$EDITOR2"&
-#COORDSEARCHPID=$!
-#if ps $COORDSEARCHPID >/dev/null; then
-#	echo "PID=$COORDSEARCHPID "
-#else
-#	echo "Couldn't start viewer loop, aborting."
-#	exit
-#fi
-#
-#
-#echo "Press enter to quit"
-#read DUMMYVAR
-#
-#coordquit
